api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    exception_to_status:
        App\Exception\SectionNotBelongToDepartmentException: 400
    eager_loading:
        force_eager: false
