api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    exception_to_status:
        App\Exception\SectionNotBelongToDepartmentException: 400
        App\Exception\IncorrectStatusChangeException: 400
    eager_loading:
        force_eager: false
    collection:
        pagination:
            enabled: true
            client_items_per_page: true
#            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 50
#            page_parameter_name: page
