ldap_tools:
  security:
    guard:
      username_parameter: username
      password_parameter: password
  domains:
    active_directory:
      domain_name: '%env(resolve:LDAP_DOMAIN)%'
      servers: ['%env(resolve:LDAP_HOST)%']
      bind_format: '%env(resolve:LDAP_BIND_FORMAT)%'
      username: '%env(resolve:LDAP_ADMIN_USERNAME)%'
      password: '%env(resolve:LDAP_ADMIN_PASSWORD)%'
